### ISSUE TITLE
6.8.3 release backport

### ISSUE THREAD

**Issue by ezimuel** [elastic/elasticsearch-php#1156]
This is a meta ticket to collect all the PRs that we would like to backport in `6.8.3`:

- [ ] Fix #1074 allowing multiple function parameters in fromConfig (see https://github.com/elastic/elasticsearch-php/pull/1076)
- [ ] 401 - Unauthorized Code Exception Handling (see https://github.com/elastic/elasticsearch-php/issues/1097)
- [ ] Remove unnecessary InvalidArgumentExceptions (see https://github.com/elastic/elasticsearch-php/commit/2215c18fa131e33f6e4af5167981b1280e6ebaa0)
- [ ] Output json_last_error_msg instead of json_last_error (see https://github.com/elastic/elasticsearch-php/pull/1045)
